apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: attendance-api
  template:
    metadata:
      labels:
        app: attendance-api
    spec:
      containers:
      - name: attendance-api
        image: attendanceacr5806.azurecr.io/attendance-api:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: attendance-api-service
spec:
  type: LoadBalancer
  selector:
    app: attendance-api
  ports:
  - port: 80
    targetPort: 8080

